# Generated by Django 3.0.5 on 2020-05-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='birthday',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
