# Generated by Django 3.0.5 on 2020-05-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='birthday',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
