# Generated by Django 3.0.5 on 2020-05-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20200528_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='add_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='birthday',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
    ]
