# Generated by Django 3.0.5 on 2020-05-28 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contact_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='add_note',
        ),
    ]
