# Generated by Django 3.0.5 on 2020-05-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_addnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='add_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='AddNote',
        ),
    ]
